### ISSUE TITLE
How do I make it work

### ISSUE THREAD

**Issue by h-bernardo** [visualcurrent/Notion-2-Obsidan#10]
I am on a windows machine, I am not much of a programmer. I don't know where to run the file, tried Windows Terminal, Python 3.8 from Microsoft Store, Anaconda Spyder, all give error somewhere

**Comment by nicknitride** [comment]
Yeah you have to install a couple of dependencies
1. easygui https://pypi.org/project/easygui/
2. and https://stackoverflow.com/questions/20044559/how-to-pip-or-easy-install-tkinter-on-windows python3-tk 
on linux step 2 is actually just **_sudo apt-get install python3-tk_**

**Comment by h-bernardo** [comment]
It worked! Thanks a lot
