### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by austkel** [visualcurrent/Notion-2-Obsidan#2]
E:\Desktop Data\Downloads\Notion-2-Obsidan-master>python N2O.py
Traceback (most recent call last):
  File "N2O.py", line 138, in <module>
    with open(newfilepath, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\owner\\AppData\\Local\\Temp\\tmppg9672w4\\Untitled\\Lime\\Write Ups.html'

When I try to open my export zip seems to hit an error

**Comment by visualcurrent** [comment]
According to your error, it appears that you are trying to open `Write Ups.html` which is not a .zip file. Can you double check the integrity and location of your downloaded zip file?

**Comment by kgilbert89** [comment]
I'm having the same issue.  I double-checked the zip for errors and the location as well. 

```
C:\Users\kayla\Downloads\Notion-2-Obsidan-master>py N2O.py
Traceback (most recent call last):
  File "N2O.py", line 98, in <module>
    with open(newfilepath, append_write) as tempFile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kayla\\AppData\\Local\\Temp\\tmp9n3jerfu\\Untitled\\ultimate db.md'
```

**Comment by visualcurrent** [comment]
Hmm? It's just not enough information for me to work with. And my Notion exports aren't creating that error.
@kgilbert89 or @austkel would it be possible to PM me the zip file for me to troubleshoot with? If so, gabe@visualcurrent.com

**Comment by visualcurrent** [comment]
Attention @kgilbert89 and @austkel 
Would you mind trying the latest code on your Notion exports and let me know if the changes work for you?
I'll close the issue if it works.
Thanks
