### ISSUE TITLE
Can't select zip

### ISSUE THREAD

**Issue by sivner-figbus** [visualcurrent/Notion-2-Obsidan#3]
Hi,

I'm trying to operate your python script following the instructions at https://github.com/visualcurrent/Notion-2-Obsidan/blob/master/README.md

When I run "Python3 N2O.py", the open file dialog appears, but I can't select any zip files within it. All the files in the dialog are greyed out and cannot be selected. 

![image](https://user-images.githubusercontent.com/67953485/92968503-28bb4780-f473-11ea-9d18-05df44575133.png)

Directories can be selected, but selecting them simply opens them - it doesn't launch your script.

Using a Mac.

If I manually edit N2O.py to hard-code the path to the zip, it seems to work:

`NotionZip = Path("/path/to/my/notionexport.zip")`

Thanks

**Comment by visualcurrent** [comment]
With the help of a couple people on Mac, hopefully this issue is solved from this commit.

https://github.com/visualcurrent/Notion-2-Obsidan/commit/53ef90a323bbde8fbc47fdfa20dd84c7e7797626
